[project]
name = "jenkins-githubaction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["api4jenkins==1.11", "requests==2.28.1"]

[tool.uv]
dev-dependencies = ["pytest>=8.3.3", "ruff>=0.6.4", "testcontainers>=4.8.1"]
